### ISSUE TITLE
Only allow public repos to be read and written by SharableHQ.

### ISSUE THREAD

**Issue by rik-rosseel** [shareableHQ/shareable#18]
Currently to add a script you have to sign in with Github and give access to all public AND private repos. I would like to upload a script but not have every repo to be accessible for SharableHQ.
The scripts end up being public when downloading them so there’s really no reason to keep the repo private.

**Comment by alombi** [comment]
Hello and thank you for opening an issue! I've just fixed the problem you mentioned, so Shareable will now ask access for public repos only. Feel free to reopen the issue if something doesn't work as expected
